

location ~ ^/sharing/([-_\w\d]+)$ {
    root    /usr/syno/synoman;
    rewrite /sharing/([^\/\.]+) /sharing.cgi?_sharing_id=$1 break;

    include             scgi_params;
    scgi_read_timeout   3600s;
    scgi_pass           synoscgi;
}

location ~ ^/sharing/(.+)\.cgi {
    root    /usr/syno/synoman;
    rewrite /sharing/(.+) /$1 break;

    include             scgi_params;
    scgi_read_timeout   3600s;
    scgi_pass           synoscgi;
}

location ~ ^/sharing/$ {
    root    /usr/syno/synoman;
    rewrite /sharing/ /sharing.cgi break;

    include             scgi_params;
    scgi_read_timeout   3600s;
    scgi_pass           synoscgi;
}

location ~ ^/sharing/errors$ {
    root    /usr/syno/synoman;
    rewrite /sharing/errors /sharing.cgi break;

    include             scgi_params;
    scgi_read_timeout   3600s;
    scgi_pass           synoscgi;
}

location ~ ^/sharing/(.+)$ {
    root    /usr/syno/synoman;
    rewrite /sharing/(.+) /$1 break;
}

location ~ /webman/modules/FileBrowser/index_ds.php$ {
	default_type    text/html;
	alias           /usr/syno/share/OAuth/index_ds.php;
}

location ~ ^/wfmlogindialog.js(.*) {
	root /usr/syno/synoman;
	rewrite /wfmlogindialog.js(.*) /webman/modules/FileBrowser/directlogin.js$1 break;
}

location ~ ^/fbsharing/(.*)$ {
	root /usr/syno/synoman;
	rewrite /fbsharing/(.*)$ $scheme://$http_host/sharing/fbsharing-$1 break;
}

location ~ ^/fsdownload/webapi/file_download\.cgi/(.*)$ {
	root /usr/syno/synoman;
	rewrite /fsdownload/webapi/file_download\.cgi/(.*)$ /webapi/_______________________________________________________entry.cgi?api=SYNO.FolderSharing.Download&version=2&method=download break;
	scgi_param   REWRITE_APP "SYNO.SDS.App.FileStation3.Instance";
	scgi_read_timeout   3600s;
	include     scgi_params;
	scgi_pass   synoscgi;

}

location ~ ^/fsdownload/(webman|scripts|synoSDSjslib)/(.*)$ {
	root /usr/syno/synoman;
	rewrite /fsdownload/(.*)$ /$1 break;
}

location ~ ^/fsdownload/webapi/(.*)$ {
	root /usr/syno/synoman;
	rewrite /fsdownload/(.*)$ /$1 break;
	scgi_param   REWRITE_APP "SYNO.SDS.App.FileStation3.Instance";
	scgi_read_timeout   3600s;
	include     scgi_params;
	scgi_pass   synoscgi;

}

location ~ ^/fsdownload/([-_\w\d]+)/(.*)$ {
	root /usr/syno/synoman;
	rewrite /fsdownload/([-_\w\d]+)/(.*)$ /webapi/_______________________________________________________entry.cgi?api=SYNO.FileStation.Sharing.Download&version=1&method=download&_sharing_id="$1"&mode=download break;
	scgi_param   REWRITE_APP "SYNO.SDS.App.FileStation3.Instance";
	scgi_read_timeout   3600s;
	include     scgi_params;
	scgi_pass   synoscgi;

}

location ~ ^/fbdownload/(.*)$ {
	root /usr/syno/synoman;
	if ($args ~* "^k=(.*)") {
		rewrite ^.*$ $scheme://$http_host/sharing/fbsharing-$arg_k? last;
	}
	rewrite /fbdownload/(.*)$ /webapi/_______________________________________________________entry.cgi?api=SYNO.FileStation.Download&version=2&method=download&mode=download&stdhtml=true break;
	scgi_param   REWRITE_APP "SYNO.SDS.App.FileStation3.Instance";
	scgi_read_timeout   3600s;
	include     scgi_params;
	scgi_pass   synoscgi;

}

location ~ ^/fbgdrivedownload/(.*)$ {
	root /usr/syno/synoman;
	rewrite /fbgdrivedownload/(.*) /webapi/_______________________________________________________entry.cgi?api=SYNO.FileStation.VFS.GDrive&method=download&version=1&mode=download&stdhtml=true break;
	scgi_param   REWRITE_APP "SYNO.SDS.App.FileStation3.Instance";
	scgi_read_timeout   3600s;
	include     scgi_params;
	scgi_pass   synoscgi;

}

location ~ ^/viewer/(.*)/(.*)/(.*)/(.*)$ {
	root /usr/syno/synoman;
	rewrite /viewer/(.*)/(.*)/(.*)/(.*) /webapi/_______________________________________________________entry.cgi?api=SYNO.FileStation.Download&version=2&method=download&dlink="$1"&_sid="$2"&SynoToken=$3&mode=open&stdhtml=true break;
	scgi_param   REWRITE_APP "SYNO.SDS.App.FileStation3.Instance";
	scgi_read_timeout   3600s;
	include     scgi_params;
	scgi_pass   synoscgi;

}

