kernel.panic = 3
net.core.somaxconn = 65535
net.ipv4.tcp_tw_reuse  = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
kernel.syno_forbid_console=0
kernel.syno_forbid_usb=0
net.ipv6.conf.default.accept_ra_defrtr=0
net.ipv4.conf.default.accept_redirects=0
net.ipv6.conf.default.accept_redirects=0
net.ipv4.conf.default.send_redirects=0
net.ipv4.conf.default.secure_redirects=0
net.ipv6.conf.default.accept_ra=0
kernel.sem=250 32000 32 256
