ssl_certificate          /usr/syno/etc/www/certificate/system_default/c89daf19-cd9d-4931-9d55-f949193d30cf.pem;
ssl_certificate_key      /usr/syno/etc/www/certificate/system_default/913c213e-977c-46c2-8232-9f6f30ba7500.pem;
