location ~ ^/d/f/ {
	root /usr/syno/synoman;
	index index.cgi;

	rewrite /d/f/([0-9a-zA-Z_]+\.(txt|cgi))$ /$1 last;
	rewrite /d/f/(webman|scripts|synoSDSjslib|synoSDSjslib-compatible-6.x|synohdpack|oauth|webapi)/(.*)$ /$1/$2 last;
	rewrite /d/f/([0-9a-zA-Z]+)$ /webapi/entry.cgi?api=SYNO.SynologyDrive.Shard&version=1&method=get&link_id="$1" break;

	include     scgi_params;
	scgi_pass   synoscgi;

}

location ~ ^/d/s/ {
	root /usr/syno/synoman;
	index index.cgi;

	rewrite /d/s/([0-9a-zA-Z]+)/([0-9a-zA-Z_]+\.(txt|cgi))$ /$2 last;
	rewrite /d/s/([0-9a-zA-Z]+)/(webman|scripts|synoSDSjslib|synoSDSjslib-compatible-6.x|synohdpack|oauth|webapi|oo|sc)/(.*)$ /$2/$3 last;
	rewrite /d/s/([0-9a-zA-Z]+)/([^/]+)$ /webapi/entry.cgi?api=SYNO.SynologyDrive.Shard&version=1&method=get&link_id="$1"&sharing_link="$2" break;

	include     scgi_params;
	scgi_pass   synoscgi;

}

