
[LUN_ddb03a94-ed3b-4ec5-bcf2-9d04ccc3d1de]
	lid=1
	pre_alloc=no
	devtype=1
	rootpath=/volume1
	restored_time=0
	uuid=ddb03a94-ed3b-4ec5-bcf2-9d04ccc3d1de
	vpd_unit_serial=ddb03a94-ed3b-4ec5-bcf2-9d04ccc3d1de
	dev_attribs=emulate_3pc:1,emulate_tpws:1,emulate_caw:1,emulate_tpu:1,can_snapshot:1
	bytes=8589934592000
	name=LUN-VMWARE01
	bkp_obj=0
	vaai_support=yes
[LUN_4be78a22-33db-4fe4-88b7-cb5785c5ec18]
	lid=2
	pre_alloc=yes
	devtype=11
	rootpath=/volume1
	restored_time=0
	uuid=4be78a22-33db-4fe4-88b7-cb5785c5ec18
	vpd_unit_serial=4be78a22-33db-4fe4-88b7-cb5785c5ec18
	dev_attribs=emulate_3pc:0,emulate_tpws:0,emulate_caw:0,emulate_tpu:0,can_snapshot:0
	bytes=1073741824000
	name=LUN-ATOMBACKUP01
	bkp_obj=0
	vaai_support=no
[LUN_84dd827d-3e8c-4807-985c-feec8bee6b09]
	lid=3
	pre_alloc=yes
	devtype=11
	rootpath=/volume1
	restored_time=0
	uuid=84dd827d-3e8c-4807-985c-feec8bee6b09
	vpd_unit_serial=84dd827d-3e8c-4807-985c-feec8bee6b09
	dev_attribs=emulate_3pc:0,emulate_tpws:1,emulate_caw:1,emulate_tpu:0,can_snapshot:0
	bytes=1073741824000
	name=FSDISK01
	bkp_obj=0
	vaai_support=no
[LUN_85b0ee28-d69e-410d-9f65-873d156a19cf]
	lid=4
	pre_alloc=yes
	devtype=11
	rootpath=/volume1
	restored_time=0
	uuid=85b0ee28-d69e-410d-9f65-873d156a19cf
	vpd_unit_serial=85b0ee28-d69e-410d-9f65-873d156a19cf
	dev_attribs=emulate_3pc:0,emulate_tpws:1,emulate_caw:1,emulate_tpu:0,can_snapshot:0
	bytes=1073741824000
	name=LUN-VMWARE02
	bkp_obj=0
	vaai_support=no
