
[iSCSI_ACL_T1_iqn.2000-01.com.synology:default.acl]
	authority=3
[iSCSI_ACL_T2_iqn.2000-01.com.synology:default.acl]
	authority=3
[iSCSI_ACL_T3_iqn.2000-01.com.synology:default.acl]
	authority=3
[iSCSI_ACL_T4_iqn.2000-01.com.synology:default.acl]
	authority=3
