min_length = "6"
min_length_enable = "yes"
included_numeric_char = "no"
mixed_case = "no"
included_special_char = "no"
exclude_username = "yes"
password_must_change= "no"
exclude_common_password = "no"
history_num = "1"
exclude_history = "no"
enable_login_prompt=no
mail_notification_days=
allow_reset_after_expired=no
password_expire_enable=no
enable_mail_notification=no
min_age_enable=no
