[mail]
sa_mail_enable="no"
mail_enable="yes"
mail_provider="smtp.gmail.com"
[pushservice]
browser="no"
mobile="no"
pushservice_enable=""
[webhook]
webhook_custom="no"
webhook_teams="no"
webhook_chat="no"
webhook_line="no"
webhook_sms="no"
webhook_enable="no"
[cms]
cms_enable="no"
