<?php

declare(strict_types=1);

namespace App\Controllers;

use App\Services\AuthService;
use PDO;
use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Twig\Environment;

/**
 * Authentication Controller: Login, logout, and profile management
 *
 * RESPONSIBILITIES:
 * - Render login form with CSRF token
 * - Process login credentials and establish session
 * - Handle logout and session destruction
 * - Display and update user profile (display name, timezone, password)
 * - Log authentication actions (login/logout/failures) to audit log
 * - Redirect authenticated users to appropriate dashboard (admin vs. tenant)
 *
 * ROUTE MAPPING:
 * - GET  /login              → showLogin()   (render login form)
 * - POST /login              → login()       (process credentials)
 * - GET  /profile            → showProfile() (render profile form)
 * - POST /profile            → updateProfile() (update display name/timezone/password)
 * - GET  /logout             → logout()      (destroy session)
 *
 * SESSION SETUP:
 * On successful login, session is populated with:
 *   - user_id: UUID of authenticated user
 *   - tenant_id: UUID of tenant (or user_id for self-owned tenants, or null for admins)
 *   - role: Either 'admin' or 'tenant'
 *   - name: User's display name
 *   - timezone: User's preferred timezone
 *
 * SECURITY FEATURES:
 * - Session regeneration on login (prevents session fixation)
 * - Redirect authenticated users away from login form
 * - Password hashing via AuthService
 * - Audit logging of all authentication events
 * - AJAX support for profile updates (XMLHttpRequest detection)
 * - Validation of required fields (display_name cannot be empty)
 *
 * AUDIT LOGGING:
 * Actions logged:
 *   - login (success)
 *   - login_failed (bad credentials, account locked, exceptions)
 *   - logout
 *
 * Log entries include: user_id, tenant_id, IP address, user agent, details JSON
 *
 * DEPENDENCIES:
 * - AuthService: Password verification, profile updates, user lookup
 * - Twig: Template rendering for login/profile forms
 * - PDO: Direct database access for audit logging
 *
 * @package App\Controllers
 */
class AuthController
{
    private Environment $view;
    private AuthService $authService;
    private string $basePath;
    private PDO $pdo;

    /**
     * Constructor: Dependency injection of view, auth service, base path, and database
     *
     * @param Environment $view       Twig template environment for rendering forms
     * @param AuthService $authService Business logic for authentication and profile updates
     * @param string      $basePath    Application base path (for generating redirect URLs)
     * @param PDO         $pdo         Database connection for audit logging
     */
    public function __construct(Environment $view, AuthService $authService, string $basePath, PDO $pdo)
    {
        $this->view = $view;
        $this->authService = $authService;
        $this->basePath = $basePath;
        $this->pdo = $pdo;
    }

    /**
     * Render user profile management form
     *
     * DISPLAY:
     * - Current user's display name
     * - Timezone selector (populated with all PHP timezone identifiers)
     * - Password change field (optional, only updated if non-empty)
     *
     * SECURITY:
     * - Requires authenticated user (no explicit check, template displays form for any logged-in user)
     * - No role-based access control (both admin and tenant users can access)
     *
     * @param Request  $request  PSR-7 request object (unused for GET)
     * @param Response $response PSR-7 response object
     *
     * @return Response HTML response with rendered profile form
     */
    public function showProfile(Request $request, Response $response): Response
    {
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        // Render profile form with timezone list for dropdown
        $body = $this->view->render('tenant/profile.twig', [
            'timezones' => \DateTimeZone::listIdentifiers(), // All PHP timezone identifiers for selector
            'active_page' => 'profile' // Highlight "Profile" in navbar
        ]);
        $response->getBody()->write($body);
        return $response;
    }

    /**
     * Render login form or redirect if already authenticated
     *
     * BEHAVIOR:
     * - If user already logged in: Redirect to dashboard (tenant) or admin panel (admin)
     * - If user not logged in: Render login form with error message (if present in query string)
     * - CSRF token passed to template (generated by middleware or login process)
     *
     * ERROR DISPLAY:
     * - Query parameter 'error' displayed at top of login form
     * - Examples: "Invalid credentials", "Session expired", etc.
     *
     * REDIRECT LOGIC:
     * - Admin users → /admin
     * - Tenant users → /dashboard
     *
     * @param Request  $request  PSR-7 request (query params contain 'error' if present)
     * @param Response $response PSR-7 response object
     *
     * @return Response HTML response (login form) or redirect response
     */
    public function showLogin(Request $request, Response $response): Response
    {
        // Ensure session started for checking login status
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        // If already authenticated, redirect to appropriate dashboard
        if (isset($_SESSION['user_id'])) {
            $redirect = $_SESSION['role'] === 'admin' ? $this->basePath . '/admin' : $this->basePath . '/dashboard';
            return $response->withHeader('Location', $redirect)->withStatus(302);
        }

        // Render login form with error message (if present in query string)
        $body = $this->view->render('auth/login.twig', [
            'error' => $request->getQueryParams()['error'] ?? null,  // From query: ?error=...
            'csrf_token' => $_SESSION['csrf_token'] ?? '' // Session CSRF token for form protection
        ]);
        $response->getBody()->write($body);
        return $response;
    }

    /**
     * Process login form submission and establish authenticated session
     *
     * FLOW:
     * 1. Extract email and password from POST request
     * 2. Call AuthService::authenticate() to verify credentials
     * 3. If successful:
     *    a. Regenerate session ID (prevents session fixation)
     *    b. Populate $_SESSION with user context (id, tenant_id, role, etc.)
     *    c. Log successful login to audit log
     *    d. Redirect to appropriate dashboard (admin vs. tenant)
     * 4. If authentication fails:
     *    a. Log failed attempt to audit log
     *    b. Redirect to login form with error message
     *
     * SESSION SETUP (on success):
     * - user_id: User's UUID (primary identifier)
     * - tenant_id: Tenant UUID OR user_id (for self-owned tenants) OR null (for admins)
     * - role: 'admin' or 'tenant' (determines authorization level)
     * - name: User's display name (for UI display)
     * - timezone: User's preferred timezone (or null)
     *
     * TENANT MAPPING LOGIC:
     * This determines which records a user can access:
     * - If user.tenant_id is set → tenant_id = user.tenant_id (explicit tenant)
     * - Else if user.role = 'tenant' → tenant_id = user.id (self-owned tenant)
     * - Else (admin) → tenant_id = null (access all tenants)
     *
     * ERROR HANDLING:
     * - AuthService throws exception for invalid credentials, locked accounts, etc.
     * - All errors logged with email and error message
     * - Generic error message returned to user (no account enumeration)
     *
     * SECURITY FEATURES:
     * - Session regeneration (prevents session fixation attacks)
     * - Exception-driven error handling (prevents information leakage)
     * - Audit logging (all attempts tracked with IP, user agent, email)
     * - Redirect after POST (prevents form resubmission)
     *
     * @param Request  $request  PSR-7 request with parsed form body (email, password)
     * @param Response $response PSR-7 response object
     *
     * @return Response Redirect response to dashboard (success) or login form (failure)
     */
    public function login(Request $request, Response $response): Response
    {
        // Extract email and password from POST body (form submission)
        $data = $request->getParsedBody();
        $email = $data['email'] ?? '';
        $password = $data['password'] ?? '';

        try {
            // Delegate credential verification to AuthService
            // This handles: password hashing, user lookup, account status checks
            $user = $this->authService->authenticate($email, $password);

            if ($user) {
                // === STEP 1: Start session if needed and regenerate ID ===
                if (session_status() === PHP_SESSION_NONE) {
                    session_start();
                }
                session_regenerate_id(true); // Prevent session fixation; true = delete old session

                // === STEP 2: Populate session with user context ===
                // Calculate tenant_id using same logic as AuthMiddleware for consistency
                $_SESSION['user_id']   = $user['id'];
                $_SESSION['tenant_id'] = $user['tenant_id'] ?: ($user['role'] === 'tenant' ? $user['id'] : null);
                $_SESSION['role']      = $user['role'];
                $_SESSION['name']      = $user['display_name'];
                $_SESSION['timezone']  = $user['timezone'] ?? null;

                // === STEP 3: Log successful login ===
                // Audit trail includes email and role for security investigation
                $this->logAction($request, 'login', 'users', $user['id'], [
                    'email' => $email,
                    'role' => $user['role']
                ], $user['id'], $_SESSION['tenant_id']);

                // === STEP 4: Redirect to appropriate dashboard ===
                $redirect = $user['role'] === 'admin' ? $this->basePath . '/admin' : $this->basePath . '/dashboard';
                return $response->withHeader('Location', $redirect)->withStatus(302);
            }

            // Authentication returned null: user not found or credential mismatch
            // Log the failed attempt for security monitoring
            $this->logAction($request, 'login_failed', 'users', null, ['email' => $email]);

            // Redirect to login form with generic error message (no account enumeration)
            return $response->withHeader('Location', $this->basePath . '/login?error=' . urlencode('Invalid credentials or account is locked'))->withStatus(302);
        } catch (\Exception $e) {
            // AuthService threw an exception (account locked, disabled, etc.)
            // Log the failure with error details
            $this->logAction($request, 'login_failed', 'users', null, ['email' => $email, 'error' => $e->getMessage()]);
            // Redirect with error message (may reveal account status in some cases)
            return $response->withHeader('Location', $this->basePath . '/login?error=' . urlencode($e->getMessage()))->withStatus(302);
        }
    }

    /**
     * Destroy session and redirect to login form
     *
     * FLOW:
     * 1. Extract user_id and tenant_id from session (if present)
     * 2. Log logout action to audit log (for security tracking)
     * 3. Destroy session (removes all $_SESSION variables)
     * 4. Redirect to login form
     *
     * SESSION CLEANUP:
     * - All session variables cleared via session_destroy()
     * - Session cookie still present (client-side), expires naturally
     * - Next request will receive new session ID
     *
     * AUDIT LOGGING:
     * - Logs logout even if session partially corrupted
     * - Uses extracted user_id/tenant_id from $_SESSION
     * - If no user_id in session, logout is not logged (guest request)
     *
     * @param Request  $request  PSR-7 request object (unused)
     * @param Response $response PSR-7 response object
     *
     * @return Response Redirect to /login (HTTP 302)
     */
    public function logout(Request $request, Response $response): Response
    {
        // Ensure session is started for access to $_SESSION
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        // Extract user context before destroying session
        $userId = $_SESSION['user_id'] ?? null;
        $tenantId = $_SESSION['tenant_id'] ?? null;

        // Log logout if user was actually authenticated
        if ($userId) {
            $this->logAction($request, 'logout', 'users', $userId, [], $userId, $tenantId);
        }

        // Destroy all session variables
        session_destroy();

        // Redirect to login form
        return $response->withHeader('Location', $this->basePath . '/login')->withStatus(302);
    }

    /**
     * Update authenticated user's profile settings
     *
     * FIELDS UPDATED:
     * - display_name: User's visible name (required, cannot be empty)
     * - timezone: Preferred timezone for timestamp display (optional)
     * - password: New password hash (optional, only if non-empty value provided)
     *
     * VALIDATION:
     * - Display name must not be empty after trimming whitespace
     * - Returns to profile form with error message if validation fails
     *
     * FLOW:
     * 1. Validate required fields (display_name not empty)
     * 2. Call AuthService::updateProfile() to persist changes
     * 3. Update session variables (name, timezone) to reflect changes immediately
     * 4. Set success message in session
     * 5. Return response:
     *    - AJAX request: JSON response with success/error
     *    - Normal request: Redirect to profile form
     *
     * DUAL RESPONSE SUPPORT:
     * - AJAX requests (X-Requested-With: XMLHttpRequest) → JSON response
     * - Browser requests → Redirect with flash message
     * - Both share same underlying business logic (AuthService call)
     *
     * ERROR HANDLING:
     * - Display name validation is synchronous (returns 302 immediately)
     * - AuthService exceptions caught and displayed to user
     * - JSON error response includes HTTP 400 status
     *
     * SESSION UPDATES:
     * - name: Updated to reflect new display_name
     * - timezone: Updated to reflect new preference
     * - success: Message for successful update
     * - error: Message for failed update (on exception)
     *
     * @param Request  $request  PSR-7 request with form body (display_name, timezone, password)
     * @param Response $response PSR-7 response object
     *
     * @return Response JSON response (AJAX) or redirect response (normal)
     */
    public function updateProfile(Request $request, Response $response): Response
    {
        // Extract form fields from POST body
        $data = $request->getParsedBody();
        $displayName = trim($data['display_name'] ?? '');
        $timezone = $data['timezone'] ?? null;
        $password = !empty($data['password']) ? $data['password'] : null; // Only set if non-empty

        // === Validation: Display name required ===
        if (empty($displayName)) {
            $_SESSION['error'] = "Display Name cannot be empty.";
            return $response->withHeader('Location', $this->basePath . '/profile')->withStatus(302);
        }

        try {
            // === Update profile in database ===
            $userId = $_SESSION['user_id'];
            $this->authService->updateProfile($userId, $displayName, $timezone, $password);

            // === Update session variables to reflect changes ===
            $_SESSION['name'] = $displayName;
            $_SESSION['timezone'] = $timezone;
            $_SESSION['success'] = "Profile updated successfully.";

            // === Determine response format based on request type ===
            if ($request->getHeaderLine('X-Requested-With') === 'XMLHttpRequest') {
                // AJAX request: return JSON response
                $response->getBody()->write(json_encode([
                    'success' => true,
                    'message' => 'Profile updated successfully.'
                ]));
                return $response->withHeader('Content-Type', 'application/json');
            }
        } catch (\Exception $e) {
            // AuthService threw an exception (validation failure, db error, etc.)
            $msg = "Failed to update profile: " . $e->getMessage();
            $_SESSION['error'] = $msg;

            // === Determine response format for error ===
            if ($request->getHeaderLine('X-Requested-With') === 'XMLHttpRequest') {
                // AJAX request: return JSON error with 400 status
                $response->getBody()->write(json_encode([
                    'success' => false,
                    'message' => $msg
                ]));
                return $response->withHeader('Content-Type', 'application/json')->withStatus(400);
            }
        }

        // Default: redirect to profile form for non-AJAX requests (both success and failure)
        // Flash messages (success/error) will be displayed by template on next render
        return $response->withHeader('Location', $this->basePath . '/profile')->withStatus(302);
    }

    /**
     * Internal helper: Write action to audit log
     *
     * PURPOSE:
     * Records all authentication-related events in audit_log table for security tracking
     * and compliance auditing. Includes request context (IP, user agent) automatically.
     *
     * PARAMETERS:
     * - action: Type of action ('login', 'logout', 'login_failed')
     * - resourceType: Optional type of resource affected (e.g., 'users')
     * - resourceId: Optional ID of resource affected (user UUID)
     * - details: Custom JSON-serializable array with action-specific info
     * - specificUserId: Override user_id (used for login_failed when no session yet)
     * - specificTenantId: Override tenant_id (used for login_failed events)
     *
     * DEFAULT BEHAVIOR:
     * - If no specificUserId given: Use $_SESSION['user_id'] (may be null for guest)
     * - If no specificTenantId given: Use $_SESSION['tenant_id'] (may be null for admin)
     * - Extracts IP address and user agent from request server params
     *
     * DATABASE COLUMNS:
     * - user_id: UUID of acting user (null if not authenticated)
     * - tenant_id: UUID of tenant context (null for admin or failed login)
     * - action: Type of action (e.g., 'login')
     * - resource_type: Type of resource affected (e.g., 'users')
     * - resource_id: ID of resource affected (e.g., user UUID)
     * - details: JSON details object
     * - ip_address: Client IP address from REMOTE_ADDR
     * - user_agent: Client user agent string from HTTP_USER_AGENT
     * - created_at: Auto-set by database trigger to NOW()
     *
     * DETAILS OBJECT EXAMPLES:
     * - login success: {'email': 'user@example.com', 'role': 'tenant'}
     * - login failed: {'email': 'user@example.com'}
     * - logout: {} (empty object)
     *
     * @param Request       $request          PSR-7 request object (for IP/user agent)
     * @param string        $action           Type of action to log
     * @param string|null   $resourceType     Type of resource affected (optional)
     * @param string|null   $resourceId       ID of resource affected (optional)
     * @param array         $details          Custom details to store as JSON (default: empty)
     * @param string|null   $specificUserId   Override user_id from session (optional)
     * @param string|null   $specificTenantId Override tenant_id from session (optional)
     *
     * @return void No return value
     */
    private function logAction(Request $request, string $action, ?string $resourceType = null, ?string $resourceId = null, array $details = [], ?string $specificUserId = null, ?string $specificTenantId = null): void
    {
        // Determine user and tenant context: use specific values if provided, otherwise from session
        $userId = $specificUserId ?? ($_SESSION['user_id'] ?? null);
        $tenantId = $specificTenantId ?? ($_SESSION['tenant_id'] ?? null);

        // Extract request context: IP address and user agent for client tracking
        $ip = $request->getServerParams()['REMOTE_ADDR'] ?? null;
        $ua = $request->getServerParams()['HTTP_USER_AGENT'] ?? null;

        // Insert audit log entry
        $stmt = $this->pdo->prepare("
            INSERT INTO audit_log (user_id, tenant_id, action, resource_type, resource_id, details, ip_address, user_agent)
            VALUES (:uid, :tid, :act, :rt, :rid, :details, :ip, :ua)
        ");

        $stmt->execute([
            'uid' => $userId,
            'tid' => $tenantId,
            'act' => $action,
            'rt' => $resourceType,
            'rid' => $resourceId,
            'details' => json_encode($details), // Serialize details array to JSON
            'ip' => $ip,
            'ua' => $ua
        ]);
    }
}
