[DB_BACKUP]
	recycle bin admin only=yes
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=no
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=yes
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,nobody
	writeable=yes
	guest ok=yes
	path=/volume1/DB_BACKUP
	skip smb perm=yes
	comment="HCM & Tally BK"
[Software]
	recycle bin admin only=no
	ftp disable modify=no
	ftp disable download=no
	write list=nobody,nobody
	browseable=yes
	mediaindex=no
	hide unreadable=no
	win share=yes
	enable recycle bin=no
	invalid users=nobody,nobody
	read list=nobody,nobody
	ftp disable list=no
	edit synoacl=yes
	valid users=nobody,nobody
	writeable=yes
	guest ok=yes
	path=/volume1/Software
	skip smb perm=yes
	comment=""
