[global]
	printcap name=cups
	winbind enum groups=yes
	include=/var/tmp/nginx/smb.netbios.aliases.conf
	password server=ADSERVER.SURVEY.LK
	min protocol=SMB2
	security=ads
	local master=no
	realm=SURVEY.LK
	passdb backend=smbpasswd
	ldap timeout=60
	printing=cups
	max protocol=SMB3
	winbind enum users=yes
	load printers=yes
	workgroup=SURVEY
