
[global]
	follow symlinks=no
	prev domain=SURVEY
	log level=0
	wide links=no
	delete veto files=no
	rpc_server:mdssvc=external
	rpc_daemon:wspd=fork
	access based share enum=no
	disable shadow copy=no
	server signing=Disabled
	msdfs root=no
	syno catia=no
	rpc_server:MsFteWds=external
	reset on zero vc=no
	smb2 leases=no
	winbind expand groups=1
	rpc_daemon:mdssd=fork
	syno wildcard search=no
	allow insecure widelinks=no
	enable veto files=no
	fruit:locking=none
	syno directory lease grant = yes
	syno directory lease grant restrict home only = yes
