<?php

declare(strict_types=1);

namespace App\DeepDive\Pipeline;

use App\DeepDive\Correlation\Incident;
use App\DeepDive\Narrator\Narrator;

/**
 * Narrate Step: Generate AI-powered incident narratives and recommendations
 *
 * PURPOSE:
 * Transforms raw incident findings into human-readable narratives using AI.
 * For each incident, generates plain-language explanation and actionable remediation advice.
 * Persists narrative and recommended_actions to deepdive_incidents table for report overlay.
 *
 * SEQUENCE:
 * Executes after CorrelateStep (receives incidents), before RenderStep
 *
 * AI INTEGRATION:
 * Uses GROQ API via Narrator class for natural language generation
 * Requires GROQ_API_KEY environment variable to be set
 * Tracks token usage across all incident narrations
 * Persists total tokens to deepdive_jobs table for cost tracking
 *
 * OPTIONAL DESIGN:
 * This step is entirely optional and graceful:
 * - If GROQ_API_KEY is unset: step skipped cleanly (returns early)
 * - If Narrator fails to configure: step skipped (API unavailable)
 * - If individual incident narration fails: tracked as fallback, pipeline continues
 * - If database update fails: logged but doesn't block step completion
 * - Missing narration column in DB: handled gracefully (pre-migration state)
 *
 * FALLBACK MECHANISM:
 * RenderStep applies narratives as overlay on rule descriptions
 * If narrative missing: renderer falls back to rule's own remediation text
 * Rule-based findings are source of truth; AI prose enhances documentation
 * Missing or incomplete narratives don't degrade report quality
 *
 * TOKEN ACCOUNTING:
 * Tracks tokens_used across all narrations for cost visibility
 * Aggregates tokens and stores on deepdive_jobs row via narrator_tokens_used column
 * Token write failures are non-fatal (optional column, may not exist pre-migration)
 *
 * OUTPUT:
 * For each incident:
 * - narrative: Plain-language explanation generated by AI
 * - recommended_actions: JSON array of specific remediation steps
 * Both fields persisted to deepdive_incidents table for RenderStep overlay
 *
 * ERROR HANDLING:
 * Per-incident failures: logged but pipeline continues (soft failure)
 * API call failures: caught, logged, marked as fallback
 * Database write failures: caught, logged, still marks step complete
 * No exception thrown (step never fatal)
 *
 * @package App\DeepDive\Pipeline
 */
final class NarrateStep implements StepInterface
{
    /**
     * Get step identifier
     *
     * @return string 'narrate'
     */
    public function id(): string { return 'narrate'; }

    /**
     * Generate narratives and recommendations for all incidents
     *
     * FLOW:
     * 1. Verify incidents exist in context (skip if empty)
     * 2. Check GROQ_API_KEY environment variable is set
     * 3. Initialize Narrator with API key (skip if config fails)
     * 4. Prepare database UPDATE statement for narrative persistence
     * 5. For each incident:
     *    a. Validate incident object (Incident instance check)
     *    b. Call Narrator::narrate() for AI-generated narrative
     *    c. Extract tokens_used for cost tracking
     *    d. Persist narrative + recommended_actions to database
     *    e. Track success/failure counts
     * 6. Aggregate token usage and persist to deepdive_jobs table
     * 7. Record completion with statistics
     *
     * PRECONDITIONS:
     * - Incidents array populated in context (from CorrelateStep)
     * - GROQ_API_KEY environment variable set
     * - Narrator configured and API accessible
     *
     * SOFT FAILURE BEHAVIOR:
     * - Skip condition: no incidents → soft skip
     * - Skip condition: API key unset → soft skip
     * - Skip condition: Narrator fails to configure → soft skip
     * - Per-incident failure: logged, counted, pipeline continues
     * - Database write failure: logged, counted, step still completes
     * - Token persistence failure: logged, non-fatal
     *
     * DATABASE:
     * Updates deepdive_incidents table:
     * - narrative: TEXT field with AI-generated plain text
     * - recommended_actions: JSONB field with array of action objects
     * Filters by incident id and tenant_id for multi-tenant safety
     *
     * TOKEN TRACKING:
     * Sums tokens_used from all successful narrations
     * Persists to deepdive_jobs.narrator_tokens_used (nullable column)
     * Non-fatal if column doesn't exist (pre-migration)
     *
     * @param PipelineContext $ctx Shared pipeline context
     *
     * @return void Updates deepdive_incidents table, records statistics in context
     *
     * @throws none Exception never thrown; all failures handled gracefully
     */
    public function run(PipelineContext $ctx): void
    {
        $ctx->startStep($this->id());

        // Get audit logger if available
        $auditLogger = $ctx->bag['audit_logger'] ?? null;
        if ($auditLogger) {
            $auditLogger->logStepStart('narrate', 'Generating AI-powered incident narratives and recommendations');
        }

        // === Extract incidents from context ===
        // In-memory array populated by CorrelateStep during incident correlation phase
        $incidents = $ctx->bag['incidents'] ?? [];
        // Soft skip if no incidents: nothing to narrate, no errors
        if (!is_array($incidents) || $incidents === []) {
            if ($auditLogger) {
                $auditLogger->logValidation('IncidentSelection', 'narrate', true, 'No incidents to narrate');
            }
            $ctx->skipStep($this->id(), 'No incidents to narrate');
            return;
        }

        if ($auditLogger) {
            $auditLogger->logValidation('IncidentCount', 'narrate', true, count($incidents) . ' incident(s)');
        }

        // === Check for GROQ API key ===
        // Try environment variable first (typical for production)
        // Fallback to $_ENV array (test/fallback)
        // This is an OPTIONAL feature: no API key = skip narration gracefully
        $apiKey = (string)(getenv('GROQ_API_KEY') ?: ($_ENV['GROQ_API_KEY'] ?? ''));
        if ($apiKey === '') {
            // Soft skip: narration is optional, pipeline continues without narratives
            // RenderStep will fall back to rule remediation text
            if ($auditLogger) {
                $auditLogger->logValidation('GROQAPIKey', 'narrate', true, 'API key not set — skipping narration');
            }
            $ctx->skipStep($this->id(), 'GROQ_API_KEY not set — skipping AI narration');
            return;
        }

        // === Initialize AI narrator ===
        // Narrator handles GROQ API communication, rate limiting, prompt engineering
        // Passes logger for diagnostic logging of API calls
        $narrator = new Narrator($apiKey, logger: $ctx->logger);
        // Some configurations may fail validation (invalid key, missing dependencies, etc.)
        if (!$narrator->isConfigured()) {
            // Soft skip: API unavailable, fall back to rule text
            if ($auditLogger) {
                $auditLogger->logValidation('NarratorConfiguration', 'narrate', false, 'Narrator failed to configure');
            }
            $ctx->skipStep($this->id(), 'Narrator refused to configure');
            return;
        }

        if ($auditLogger) {
            $auditLogger->logValidation('NarratorConfiguration', 'narrate', true, 'Narrator initialized and ready');
        }

        // === Initialize counters and prepare statement ===
        $ok     = 0;     // Successfully narrated incidents
        $failed = 0;     // Incidents that failed narration or DB write
        $tokens = 0;     // Total GROQ tokens consumed

        // Prepare single UPDATE statement for all incidents (batch efficiency)
        // PostgreSQL ::jsonb cast ensures recommended_actions stored as JSONB type
        // Filters by tenant_id for multi-tenant isolation (RLS would also enforce this)
        $upd = $ctx->pdo->prepare("
            UPDATE deepdive_incidents
            SET narrative = :narr,
                recommended_actions = :acts::jsonb
            WHERE id = :id AND tenant_id = :tid
        ");

        // === Process each incident through narration pipeline ===
        foreach ($incidents as $inc) {
            // Validate incident object type (defensive against context corruption)
            if (!$inc instanceof Incident) { $failed++; continue; }

            // === Call AI narrator to generate narrative ===
            // Narrator::narrate() returns array with:
            // - narrative: string with plain-language explanation
            // - recommended_actions: array of remediation steps
            // - tokens_used: integer tokens consumed from API quota
            // Returns null if API call fails or response invalid
            try {
                $result = $narrator->narrate($inc);
            } catch (\Throwable $e) {
                // Unexpected exception (network, API error, etc.)
                $ctx->logger->warning('[deepdive.narrate] unexpected: ' . $e->getMessage());
                $failed++;
                continue;
            }

            // Check if narration succeeded
            if ($result === null) { $failed++; continue; }

            // === Accumulate token usage for cost tracking ===
            // Sum tokens across all incidents for total API spend
            // Used for cost visibility and quota management
            $tokens += (int)($result['tokens_used'] ?? 0);

            // === Persist narrative to database ===
            // Narrative and recommendations stored for RenderStep overlay
            // If database write fails: incident falls back to rule text (not fatal)
            try {
                $upd->execute([
                    'id'   => $inc->id,
                    'tid'  => $ctx->tenantId,
                    'narr' => $result['narrative'],
                    // json_encode() converts recommended_actions array to JSON
                    // JSON_UNESCAPED_SLASHES preserves URL formatting in recommendations
                    'acts' => json_encode($result['recommended_actions'], JSON_UNESCAPED_SLASHES),
                ]);
                $ok++;
            } catch (\Throwable $e) {
                // Database write error: log incident ID for investigation
                // Incident will still render, just without AI narrative
                $ctx->logger->warning('[deepdive.narrate] db update failed: ' . $e->getMessage(), [
                    'incident_id' => $inc->id,
                ]);
                $failed++;
            }
        }

        // === Persist token usage to job record ===
        // Updates deepdive_jobs.narrator_tokens_used for cost tracking and visibility
        // Column is NULLABLE to handle pre-migration state (column may not exist yet)
        // Token persistence failure is non-fatal: doesn't affect pipeline or report
        // Only attempt write if tokens > 0 (avoid unnecessary database hits)
        if ($tokens > 0) {
            try {
                $ctx->pdo->prepare(
                    "UPDATE deepdive_jobs SET narrator_tokens_used = :n WHERE id = :id"
                )->execute(['n' => $tokens, 'id' => $ctx->jobId]);
            } catch (\Throwable $e) {
                // Log failure but don't block pipeline
                // Pre-migration system may not have narrator_tokens_used column
                $ctx->logger->warning('[deepdive.narrate] token write failed: ' . $e->getMessage());
            }
        }

        // === Record statistics and mark complete ===
        // Store token usage in context for downstream steps/report
        $ctx->bag['narrator_tokens_used'] = $tokens;

        // Log step completion
        if ($auditLogger) {
            $auditLogger->logStepComplete('narrate', 'AI narration complete', [
                'incidents_narrated' => $ok,
                'incidents_fallback' => $failed,
                'tokens_used' => $tokens,
            ]);
        }

        // Status string shows: successful narrations, fallback count, tokens used
        // Example: "42 narrated, 8 fell back to rule text, 3204 tokens"
        $ctx->stepDetail($this->id(), "{$ok} narrated, {$failed} fell back to rule text, {$tokens} tokens");

        // Mark step complete (soft step: never throws, always marks done)
        $ctx->completeStep($this->id());
    }
}
