
[iSCSI_T1]
	authen=no
	max_sessions=1
	network_portals={all}:3260
	tid=1
	data_chksum=no
	recv_seg_bytes=262144
	enabled=yes
	mutual=no
	iqn=iqn.2000-01.com.synology:JJETNAS01.VMWARE01
	name=VMWARE01
	hdr_chksum=no
	send_seg_bytes=262144
	bkp_obj=0
[iSCSI_T2]
	authen=no
	max_sessions=1
	network_portals={all}:3260
	tid=2
	data_chksum=no
	recv_seg_bytes=262144
	enabled=yes
	mutual=no
	iqn=iqn.2000-01.com.synology:JJETNAS01.ATOMBACKUP01
	name=ATOMBACKUP01
	hdr_chksum=no
	send_seg_bytes=262144
	bkp_obj=0
[iSCSI_T3]
	authen=no
	max_sessions=1
	network_portals={all}:3260
	tid=3
	data_chksum=no
	recv_seg_bytes=262144
	enabled=yes
	mutual=no
	iqn=iqn.2000-01.com.synology:JJETNAS01.FSDISK01
	name=FSDISK01
	hdr_chksum=no
	send_seg_bytes=262144
	bkp_obj=0
[iSCSI_T4]
	authen=no
	max_sessions=1
	network_portals={all}:3260
	tid=4
	data_chksum=no
	recv_seg_bytes=262144
	enabled=yes
	mutual=no
	iqn=iqn.2000-01.com.synology:JJETNAS01.VMWARE02.a926480b5a
	name=VMWARE02
	hdr_chksum=no
	send_seg_bytes=262144
	bkp_obj=0
