[LUN_5c97d959-8fce-453c-b210-4d72e4da8fd4]
lid=2
rootpath=/volume1
name=ITVMLUN
uuid=5c97d959-8fce-453c-b210-4d72e4da8fd4
vpd_unit_serial=5c97d959-8fce-453c-b210-4d72e4da8fd4
bytes=8246337208320
restored_time=0
devtype=1
dev_attribs=emulate_3pc:1,emulate_tpws:1,emulate_caw:1,emulate_tpu:1,emulate_fua_write:0,emulate_sync_cache:0,can_snapshot:1
pre_alloc=no
bkp_obj=0
vaai_support=yes
direct_io_pattern=0
description=
dev_config=
inquiry_prod=iSCSI Storage
dev_qos=iops_enable:0,dev_limit:0,dev_reservation:0,dev_weight:0
create_from=
max_snapshot_count=256
[LUN_adc4e1b1-670f-45c3-9897-aea1fc4145c9]
lid=1
rootpath=/volume1
name=VMBACKUP
uuid=adc4e1b1-670f-45c3-9897-aea1fc4145c9
vpd_unit_serial=adc4e1b1-670f-45c3-9897-aea1fc4145c9
bytes=4398046511104
restored_time=0
devtype=11
dev_attribs=emulate_3pc:0,emulate_tpws:0,emulate_caw:0,emulate_tpu:0,emulate_fua_write:0,emulate_sync_cache:0,can_snapshot:0
pre_alloc=yes
bkp_obj=0
vaai_support=no
direct_io_pattern=0
description=
dev_config=
inquiry_prod=iSCSI Storage
dev_qos=iops_enable:0,dev_limit:0,dev_reservation:0,dev_weight:0
create_from=
max_snapshot_count=256
