location ~ ^/webman/pingpong.cgi {
	default_type text/plain;
	root /usr/syno/synoman;
	if ($arg_quickconnect) {
		add_header Access-Control-Allow-Origin *;
		return 200 '{"success": true, "ezid": "4c20941891751b1a5e5373631da96138"}';
	}
	include	scgi_params;
	scgi_pass synoscgi;
}
